name: mybible_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  percent_indicator: ^2.1.1+1

  html_unescape: ^2.0.0

  html: ^0.15.0

  shared_preferences: ^2.0.6

  test: ^1.9.4

flutter:

  uses-material-design: true
  assets:
    - image/
    - image/001.png
    - image/002.png
    - image/003.png
    - image/004.png
    - image/005.png
    - image/bible.png
fonts:
  - familly: NanumGothic
    fonts:
      - asset: fonts\NanumGothic-Bold.ttf
      - asset: fonts\NanumGothic-ExtraBold.ttf
      - asset: fonts\NanumGothic-Regular.ttf





